---
dist: focal

before_install:
  # Currently installed version of docker-compose is out-dated:
  - pip install -U docker-compose
  - pip install -U -r requirements.txt
  - npm install
  - sudo curl -fsSL https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
  - sudo chmod +x /usr/local/bin/hadolint

script:
  - npm test
  - mkdocs build

notifications:
  email:
    on_success: never
    on_failure: always
