os: linux

language: node_js

node_js:
  - "lts/*"

before_install:
  - npm i -g npm
  - npm install --save-dev

script:
  - npm doctor
  # TODO Check for out-dated packages without failing on markdown-spelling:
  #- npm outdated
  - npm audit
  - npm test

notifications:
  email:
    on_success: never
    on_failure: always
