site_name: IT documentation with i-doit
site_url: https://docs.i-doit.com/
site_description: Documentation of CMDB & IT documentation application i-doit
site_author: synetics GmbH
copyright: Copyright &copy; 2019
google_analytics:
  - 'UA-66601150-16'
  - 'docs.i-doit.com'
#repo_url: https://github.com/i-doit/docs/
#edit_uri: edit/dev/docs/
edit_uri: https://github.com/i-doit/docs/edit/master/docs/
strict: true
theme:
  name: material
  custom_dir: theme
  palette:
    primary: black
    accent: red
  font: false
  logo: img/i-doit-icon.png
  language: en
  favicon: img/favicon.png
  feature:
    tabs: false
plugins:
  - search:
      lang: ['en']
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - meta
  - toc:
      permalink: "#"
extra:
# https://developers.google.com/web/fundamentals/web-app-manifest/
#  manifest: 'manifest.webmanifest'
  social:
    - type: 'globe'
      link: 'https://i-doit.com'
    - type: 'comments'
      link: 'https://community.i-doit.com'
    - type: 'life-ring'
      link: 'https://help.i-doit.com'
    - type: 'play'
      link: 'https://demo.i-doit.com'
    - type: 'twitter'
      link: 'https://twitter.com/i_doit'
    - type: 'xing'
      link: 'https://www.xing.com/communities/groups/i-doit-dokumentation-und-cmdb-1064322'
    - type: 'youtube'
      link: 'https://www.youtube.com/user/smartitsm'
    - type: 'facebook'
      link: 'https://facebook.com/itdokumentation/'
use_directory_urls: false
nav:
  - Overview: index.md
  - User Guide:
      - Login: user/login.md
#      - Dashboard: user/dashboard.md
      - Objects:
          - Create and edit: user/objects/create-and-edit.md
          - Archive, delete and purge: user/objects/archive-delete-and-purge.md
          - History: user/objects/history.md
      - Documentation basics:
          - Collections: user/basics/collections.md
          - Classes: user/basics/classes.md
          - Objects: user/basics/objects.md
          - Categories and attributes: user/basics/categories-and-attributes.md
      - Finder:
          - Views: user/finder/views.md
          - Presets: user/finder/presets.md
          - Search and filter: user/finder/search-and-filter.md
          - Export and print: user/finder/export-and-print.md
          - Inline editing: user/finder/inline-editing.md
      - Imports:
          - CSV: user/imports/csv.md
      - User settings: user/settings.md
#      - Examples:
#          - Server hardware: user/examples/server-hardware.md
  - Admin Guide:
      - Users and roles: admin/users-and-roles.md
      - Documentation settings:
          - Collections: admin/documentation-settings/collections.md
          - Classes: admin/documentation-settings/classes.md
          - Categories: admin/documentation-settings/categories.md
#      - System settings: admin/system-settings.md
#      - Distribution Center: admin/distribution-center.md
#  - Installation:
#      - Installation:
#          - Manual Instructions:
#              - Debian: installation/debian.md
#              - Red Hat Enterprise Linux (RHEL): installation/rhel.md
#              - Ubuntu: installation/ubuntu.md
#              - Suse Linux Enterprise Server (SLES): installation/sles.md
#              - Microsoft Windows Server: installation/windows.md
#              - OS Settings: installation/os-settings.md
#              - Setup: installation/setup.md
#          - Docker Container: installation/docker-container.md
#          - Virtual Appliance: installation/virtual-appliance.md
#      - Maintenance:
#          - Subscriptions: installation/subscriptions.md
#          - Cronjobs: installation/cronjobs.md
#          - Backup and Recovery: installation/backup-and-recovery.md
#          - Updates: installation/updates.md
#          - Security: installation/security.md
#          - Performance: installation/performance.md
#          - Maintenance Mode: installation/maintenance-mode.md
#      - Migration:
#          - Migrate from 1.x to 2.x: installation/migrate-from-1.x-to-2.x.md
#      - Command-line interface (CLI): installation/cli.md
  - API:
     - Introduction: api/index.md
     - Examples: api/examples.md
     - Reference v1: api/reference/v1/index.html
#  - Add-ons:
#     - Introduction: add-ons/index.md
#     - Documents:
#         - About: add-ons/documents/index.md
#         - Changelogs: add-ons/documents/changelogs.md
#  - Development Partners:
#     - Introduction: dev/index.md
  - Technical reference:
      - Version history: ref/version-history.md
      - Release Notes: ref/release-notes.md
      - Changelogs: ref/changelogs.md
      - System Requirements: ref/system-requirements.md
      - License: ref/license.md
      - Database schema: ref/database-schema.md
      - List of collections: ref/list-of-collections.md
      - List of classes: ref/list-of-classes.md
      - List of categories: ref/list-of-categories.md
